# fly.toml file generated for cognite-python-copilot on 2023-03-28T00:32:57+02:00

app = "cognite-python-copilot"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "arn"

[build]
  [build.args]
    NEXT_PUBLIC_EXAMPLE = "Value goes here"
    NODE_VERSION = "18"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
